spring:
  h2.console:
    enabled: true
    path: '/console'
  datasource:
    url: 'jdbc:h2:file:C:\\Users\\aggie\\Desktop\\medical-app\\medication-db'
  jpa:
    hibernate:
      ddl-auto: validate
management:
  endpoints:
    web:
      exposure:
        include: '*'
keycloak:
  auth-server-url: 'http://localhost:8180/auth'
  realm: 'MedicationApp'
  resource: 'Medication-spring-client'
  public-client: true